"""City-specific notes for scripts/ny_verified_hubs.py. Plain, checkable local context only.
No rebate numbers here - those live in data/verified-facts/ny.json / U in ny_verified_hubs.py."""

LOCAL = {
 'con-edison/new-york-city': dict(
   more=['Steam heat is the big NYC question. Many pre-war buildings run one-pipe or two-pipe steam boilers, and a heat pump has to replace that heat room by room, often with ductless heads. A contractor who has done brownstone and row-house jobs will size this better than one who mostly installs central systems in the suburbs.',
         'Co-op and condo owners usually need board approval for outdoor units, and some buildings restrict units on the street side. Owners of 1&ndash;4 family houses can apply directly. Renters in these buildings may still qualify for EmPower+ even though the landlord owns the heating system.',
         'NYC&rsquo;s Local Law 97 mostly targets buildings over 25,000 sq ft, so it rarely applies to a one- to four-family home &mdash; but it is why some larger co-ops are already planning building-wide electrification.'],
   steps=['Find out if your heat is steam, hot water or forced air &mdash; it changes which heat pump design fits.',
          'If you are in a co-op or condo, ask the board about rules for outdoor units before you get quotes.'],
   faq=('Can I get the Con Edison rebate if I live in a co-op or condo?', 'Individual apartment owners can qualify at the apartment amounts, but you will usually need your board to approve the outdoor unit. Whole-building projects in larger buildings go through Con Edison\'s multifamily program instead.')),
 'con-edison/yonkers': dict(
   more=['Yonkers has a lot of two- and three-family houses from the early 1900s, many heated by oil or gas boilers with radiators. Ductless mini-splits are the usual fit because there are no ducts to reuse, and each unit may need its own outdoor condenser.',
         'Because the Con Edison program covers 1&ndash;4 family buildings, an owner who lives in one unit of a two-family can often do both units in one project. Ask whether your contractor is pricing the single-family or apartment tier for each unit.',
         'Hilly streets and tight side yards are common, so ask where the outdoor units will sit and how loud they are next to your neighbour&rsquo;s windows.'],
   steps=['If you own a two- or three-family, ask for one quote covering every unit.',
          'Confirm with the contractor that your electrical panel can take the new load.'],
   faq=('Can I do a two-family house in Yonkers?', 'Yes. Con Edison\'s residential program covers 1-4 family buildings, so you can usually include every unit. Each unit is priced at the tier that fits it, so ask your contractor to show the math.')),
 'con-edison/new-rochelle': dict(
   more=['New Rochelle has a wide mix of homes, from large older houses near the Sound to post-war capes and newer downtown apartments. Bigger older homes often need a multi-zone system, which raises the price but not the rebate cap, so insulation first matters here.',
         'Coastal flooding is a real concern in low-lying neighbourhoods near the water. Ask your installer to mount outdoor units on raised stands or brackets if you are in a flood zone.',
         'Downtown condo owners should look at the apartment amounts in the table, and check building rules before planning a unit on a balcony or roof.'],
   steps=['If you are near the water, ask about raised mounting for outdoor units.',
          'Get an energy audit on larger older homes before you size the system.'],
   faq=('Does it matter if my New Rochelle home is in a flood zone?', 'It does not change the rebate, but it changes the install. Outdoor units should be raised above expected flood levels, which can add some cost, so ask for it in writing on the quote.')),
 'con-edison/mount-vernon': dict(
   more=['Mount Vernon is one of the most densely built cities in Westchester, with many older two-family homes and small apartment buildings. Owner-occupants of 1&ndash;4 family buildings can use the Con Edison program for every unit.',
         'Because parts of the city are Disadvantaged Communities, the same project can earn a higher Clean Heat amount and a higher cost cap depending on the exact address. Two neighbours on different blocks can get different numbers.',
         'Lower-income owners and renters should look at EmPower+ first, since it can pay for insulation and air sealing at no cost and make the heat pump smaller.'],
   steps=['Look up your exact address on the DAC map before you compare quotes.',
          'If money is tight, apply to EmPower+ first, then plan the heat pump.'],
   faq=('Why did my neighbour get a bigger rebate than my quote shows?', 'Disadvantaged Community status is set by census tract, so homes a few blocks apart can fall on different sides of the line. DAC homes get higher Con Edison amounts and an 85% cost cap instead of 70%.')),
 'con-edison/white-plains': dict(
   more=['White Plains has many 1950s&ndash;80s single-family homes with ducts already in place for central air. When the ducts are in good shape, a ducted cold-climate heat pump can replace the furnace and the AC in one step.',
         'The city also has lots of condos and co-ops downtown, where the apartment amounts apply and board approval is often needed for outdoor equipment.',
         'Westchester County has its own programs from time to time, so ask your contractor whether a county incentive is open when you apply &mdash; but don&rsquo;t count on one until it is confirmed in writing.'],
   steps=['Have your ducts checked for leaks and size before choosing a ducted system.',
          'Condo owners: ask your board about rules for outdoor units first.'],
   faq=('Can I reuse my ducts in White Plains?', 'Often, yes. Many homes here have central air ducts. A contractor should test them for leaks and size; leaky or undersized ducts should be fixed or the system will not keep up in winter.')),
 'national-grid/buffalo': dict(
   more=['Buffalo&rsquo;s housing is old: many homes are wood-frame doubles (two-family flats) and bungalows built before 1940, often with little wall insulation. That is why insulation is such a common search here &mdash; it usually pays back faster than anything else.',
         'Winters are cold and snowy, so a cold-climate heat pump should be sized with a proper load calculation, and many Buffalo homes keep their gas furnace as backup for the coldest nights. That usually counts as a partial system, which earns the smaller partial-load amount.',
         'Outdoor units need to sit above the snow line and away from roof drip edges, where ice can build up.'],
   steps=['Start with attic insulation and air sealing &mdash; it makes every heat pump option cheaper.',
          'Decide early if you will keep your gas furnace as backup, because it changes which rebate tier you get.'],
   faq=('Is there an insulation rebate in Buffalo?', 'Yes, through NYSERDA\'s Comfort Home ($2,500-$3,000 per package, plus $2,000 for windows) and, if your income qualifies, EmPower+. The federal 25C insulation credit ended December 31, 2025.')),
 'national-grid/syracuse': dict(
   more=['Syracuse gets some of the heaviest snow of any US city, and many homes are older two-family houses and bungalows near the university and downtown. Cold-climate sizing and good snow clearance for the outdoor unit matter more here than in most places.',
         'Because National Grid supplies both gas and electricity in Syracuse, you will see both sides of the bill change after a switch. Removing the gas furnace entirely earns the larger &ldquo;with decommissioning&rdquo; amount, but only do that if the heat pump is sized for the coldest days.',
         'Parts of the city are Disadvantaged Communities, which raises the National Grid amounts &mdash; check your address.'],
   steps=['Ask for a room-by-room load calculation (Manual J), not a rule-of-thumb size.',
          'Check your address on the DAC map &mdash; many Syracuse neighbourhoods qualify.'],
   faq=('Will a heat pump keep up in a Syracuse winter?', 'A cold-climate model sized with a proper load calculation can, and Clean Heat requires cold-climate equipment. Many homeowners keep a backup for the coldest nights, which usually puts them on the partial-load rebate instead of the full-load one.')),
 'national-grid/albany': dict(
   more=['Albany&rsquo;s classic brick row houses share walls, which helps them hold heat, but their tall ceilings and old windows lose it. Ductless heads are the common choice because most row houses heat with radiators and have no ducts.',
         'In a two-family house, each unit can count as an apartment for the rebate. Ask your contractor whether they are pricing your home as one single-family system or two apartments.',
         'Historic districts may have rules about where equipment can go on the street side, so plan for the outdoor unit in the back or on the roof.'],
   steps=['If you are in a historic district, ask the city about rules for outdoor units.',
          'Ask whether your two-family is being priced as one home or two apartments.'],
   faq=('Do Albany historic district rules affect a heat pump?', 'They can affect where the outdoor unit goes, especially on a street-facing wall. They do not change the rebate. Check with the city before you sign so the install plan does not have to change.')),
 'national-grid/rochester': dict(
   more=['Rochester has a large stock of early-1900s single-family homes with basements and forced-air or hot-water heat. Homes with ducts can often use a ducted heat pump, while radiator homes usually need ductless heads.',
         'Lake-effect snow off Lake Ontario means the outdoor unit needs a stand above the snow line. RG&amp;E, like the other upstate utilities, only pays Clean Heat for cold-climate listed equipment.',
         'RG&amp;E and NYSEG are sister utilities, so you may see their names together on program pages. The Rochester amounts are RG&amp;E&rsquo;s, which are slightly different from NYSEG&rsquo;s in Disadvantaged Communities.'],
   steps=['Check the name on your bill: RG&amp;E in the city, but some suburbs differ.',
          'Ask for a snow stand for the outdoor unit in the quote.'],
   faq=('Is Rochester served by National Grid or RG&E?', 'The City of Rochester is served by RG&E (Rochester Gas and Electric). RG&E runs NYS Clean Heat here, paying up to $10,000 for a whole-home switch. A few outlying towns are on National Grid, so check your bill.')),
 'central-hudson/poughkeepsie': dict(
   more=['Poughkeepsie mixes older city homes near downtown and the waterfront with post-war suburbs in the Town of Poughkeepsie. City homes often have radiators and no ducts; suburban homes more often have ducts that can be reused.',
         'Oil and propane are still common in the area, and those homes see the biggest bill drop after switching. Removing the old system is what moves you from Central Hudson&rsquo;s $4,000 tier to the $7,000 tier ($8,000 to $12,000 in the Weatherized Tier).',
         'Central Hudson supplies both gas and electricity here, so gas homes can switch too, though savings versus gas are usually smaller than versus oil.'],
   steps=['If you heat with oil or propane, ask for a quote that removes the old system &mdash; it earns the higher tier.',
          'Ask whether your ducts can be reused before you choose ductless.'],
   faq=('How do I get the $7,000 Central Hudson rebate instead of $4,000?', 'The $7,000 tier is for a whole-home heat pump where the old fossil heating system is removed (decommissioned). If you keep the old system as backup, the amount is lower. The Weatherized Tier raises $4,000 to $8,000 and $7,000 to $12,000.')),
 'central-hudson/beacon': dict(
   more=['Beacon&rsquo;s older homes near Main Street are often narrow lots with little room for outdoor equipment, so ask about wall brackets or roof mounts early.',
         'Many homes here were built long before insulation codes, so a Comfort Home seal-and-insulate package is often the best first step before sizing a heat pump.'],
   steps=['Ask where the outdoor unit can go on a narrow lot before you choose a system.',
          'Consider a Comfort Home insulation package first.'],
   faq=('Is Beacon served by Central Hudson?', 'Yes. Beacon is in Central Hudson\'s territory, so the Central Hudson NYS Clean Heat amounts apply: $5,000 for a whole-home heat pump, or $8,000 if the old fossil system is removed.')),
 'central-hudson/kingston': dict(
   more=['Kingston has one of the oldest housing stocks in the state, including stone houses in the Stockade District. Thick masonry walls hold heat well but make running lines for ductless units harder, so expect a longer install.',
         'Historic-district rules may affect where equipment goes on street-facing walls, so check with the city before you sign.'],
   steps=['If you are in a historic district, check the rules for outdoor units.',
          'Get quotes that remove your oil or propane system for the higher tier.'],
   faq=('Can I put a heat pump on a historic Kingston house?', 'Yes. The rebate is the same; the install may need to keep outdoor units out of sight from the street. Check the city\'s historic district rules before you sign.')),
 'central-hudson/newburgh': dict(
   more=['Newburgh&rsquo;s East End has many large 19th-century brick row houses, often split into apartments. Owner-occupants of 1&ndash;4 unit buildings can do every unit, with the apartment amounts applying to each one.',
         'Low-income owners and renters should apply to EmPower+ first, since it can pay for air sealing and insulation at no cost.'],
   steps=['Check whether your bill says Central Hudson or O&amp;R.',
          'Apply to EmPower+ first if your income may qualify.'],
   faq=('Is Newburgh Central Hudson or Orange & Rockland?', 'The City of Newburgh is Central Hudson. Other parts of Orange County are on Orange & Rockland, which has its own Clean Heat amounts. The name on your electric bill decides which applies.')),
 'central-hudson/saugerties': dict(
   more=['Many Saugerties homes are on wells and septic and far from gas lines, and some are seasonal or older farmhouses. A home that is only lived in part of the year should still be sized for the whole house, since that is what Clean Heat pays for.',
         'Long electrical runs and older panels are common in rural homes, so ask your contractor to check your service size early.'],
   steps=['Have an electrician check your panel and service size first.',
          'If you heat with oil or propane, get a quote that removes the old system.'],
   faq=('Can I get the Central Hudson rebate on a rural Saugerties home with no gas?', 'Yes. Oil and propane homes qualify, and removing that old system earns Central Hudson\'s higher $7,000 tier for a single-family home ($12,000 in the Weatherized Tier).')),
 'pseg/brookhaven': dict(
   more=['Brookhaven covers a huge area, from dense neighbourhoods near the LIRR to rural areas out east. Homes west of the town often have gas; many further east heat with oil.',
         'The Town of Brookhaven has run a Long Island Green Homes program for income-eligible residents; check with the town for what is open now before counting on it.',
         'Older homes around Port Jefferson, Setauket and Patchogue often have boilers and radiators, while newer subdivisions in the middle of the town usually have ducts. That split decides whether a ductless or ducted system makes sense, and it changes the price a lot more than it changes the rebate.'],
   steps=['Check if your home is on gas or oil &mdash; oil homes save the most.',
          'Ask the Town of Brookhaven if its Green Homes program is taking applications.'],
   faq=('Does Brookhaven have its own energy program?', 'The Town of Brookhaven has run a Long Island Green Homes program for income-eligible residents. Ask the town what is open now; the PSEG Long Island heat pump rebate applies either way.')),
 'pseg/islip': dict(
   more=['Islip&rsquo;s south-shore neighbourhoods are close to the Great South Bay, so homes in flood zones should have outdoor units raised on stands.',
         'Many homes have forced-air systems with existing ducts, which can make a ducted heat pump simpler than a ductless one.',
         'Islip includes hamlets like Bay Shore, Brentwood, Central Islip and Sayville, and parts of the town are mapped as Disadvantaged Communities. On Long Island that moves a market-rate home from $4,000 to $5,000, so it is worth checking your exact address.'],
   steps=['If you are near the bay, ask for raised outdoor units.',
          'Ask whether your existing ducts can be reused.'],
   faq=('Does being near the Great South Bay change my heat pump install?', 'It does not change the PSEG rebate, but homes in flood zones should raise outdoor units above expected flood levels. Ask your installer to include it in the quote.')),
 'pseg/huntington': dict(
   more=['The Town of Huntington has run its own energy programs in the past, including one that paired residents with local energy auditors. Ask the town what is running now.',
         'Many North Shore homes sit on hills with long driveways and big lots, so there is usually room for outdoor units, but older wiring may need an upgrade.'],
   steps=['Ask the Town of Huntington if any local energy program is open.',
          'Get a Manual J load calculation &mdash; PSEG needs whole-home sizing.'],
   faq=('Why does PSEG Long Island require whole-home sizing?', 'PSEG\'s heat pump rebate is for a system sized to heat the entire home, so contractors must show a load calculation. A single ductless head for one room will not qualify.')),
 'pseg/oyster-bay': dict(
   more=['The Town of Oyster Bay stretches from the North Shore to the South Shore across Nassau County, with a mix of large older estates and dense post-war developments like Levittown-style capes and ranches.',
         'Post-war capes and ranches are often easy candidates: simple layouts and existing ducts in many of them.'],
   steps=['If your home is a post-war cape or ranch, ask about a ducted system using your existing ducts.',
          'Compare your gas bill to a heat pump estimate before deciding.'],
   faq=('Is a heat pump worth it in Oyster Bay if I already have gas?', 'It can be, especially if you also need new AC, since one system does both. The savings versus gas are smaller than versus oil, so ask for a bill estimate with your actual rates.')),
 'pseg/smithtown': dict(
   more=['Smithtown has many split-levels and high ranches from the 1960s and 70s, often with ducts for central air. These layouts usually work well with a ducted or mixed ducted-and-ductless setup.',
         'Plenty of homes still burn heating oil, and oil-to-heat-pump switches are where Long Island homeowners see the biggest drop in heating costs.'],
   steps=['If you have oil heat, ask for a whole-home switch quote.',
          'Ask if your existing AC ducts can be reused.'],
   faq=('Can I keep my oil boiler as backup and still get the PSEG rebate?', 'PSEG\'s rebate is for a heat pump sized to heat the whole home. Ask your participating contractor how PSEG treats backup systems on your project before you sign.')),
 'pseg/southampton': dict(
   more=['Large homes and second homes are common here. A bigger house means a bigger system and a higher price, but the PSEG rebate is a flat amount per home, so the rebate covers a smaller share.',
         'Salt air near the ocean and bays can shorten the life of outdoor units, so ask about coastal-rated coatings.'],
   steps=['Ask about coastal-rated outdoor units if you are near salt water.',
          'For a second home, ask how PSEG treats seasonal occupancy before you sign.'],
   faq=('Is the PSEG rebate bigger for a big Southampton house?', 'No. PSEG Long Island pays a flat amount per home ($4,000 at market rate), so on a large house it covers a smaller share of the cost.')),
}
